services:
  mlflow:
    image: python:3.9-slim
    container_name: mlflow-server
    working_dir: /mlflow
    ports:
      - "4999:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./registry_db:/mlflow/registry_db
    command: >
      sh -c "pip install mlflow &&
             mlflow server \
             --backend-store-uri sqlite:///mlflow/registry_db/mlflow.db \
             --default-artifact-root file:/mlflow/mlruns" \
             --host 0.0.0.0 \
             --port 5000

  api:
    build: .
    container_name: diabetes-api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/app/mlruns
