services:
  api:
    build: .
    container_name: diabetes-api
    ports:
      - "9003:9003"
    environment:
      MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
      MLFLOW_S3_ENDPOINT_URL: $MLFLOW_S3_ENDPOINT_URL
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
