services:
  api:
    build: .
    container_name: diabetes-api
    ports:
      - "9003:9003"
    environment:
      - MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
      - MLFLOW_REGISTRY_URI=$MLFLOW_TRACKING_URI
      - MLFLOW_S3_ENDPOINT_URL=$MLFLOW_S3_ENDPOINT_URL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - APP_API_KEY=$APP_API_KEY
      - APP_API_URL=$APP_API_URL
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_URL=$DATABASE_URL
      - STAGE=$STAGE
      - EXPERIMENT_NAME=$EXPERIMENT_NAME
      - REGISTERED_MODEL_NAME=$REGISTERED_MODEL_NAME
  prometheus:
    image: prom/prometheus
    ports:
      - "9005:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus.yml
    # command:
    #   - "--config.file=/prometheus/prometheus.yml"
    #   - '--storage.tsdb.path=/prometheus'
    #   - '--web.console.libraries=/etc/prometheus/console_libraries'
    #   - '--web.console.templates=/etc/prometheus/consoles'
    #   - '--web.enable-lifecycle'
    depends_on:
      - api
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "9006:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus_data:
