name: Train, Register, and Deploy ML Model

on:
  push:
    branches: [master]
jobs:
  train-register-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv pip install -r requirements.txt --system
      - name: Configure DVC
        run: |
          dvc remote modify origin access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}
          dvc remote modify origin secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Pull data with DVC
        run: |
          dvc pull -v

      - name: Run Training
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: ${{ secrets.STAGE }}
        run: |
          python train.py
      - name: Reload API model
        run: |
          curl -X POST https://diabetes.machinelearningdev.com/reload \
            -H "x-api-key: ${{ secrets.RELOAD_API_KEY }}"
